# Generated by Django 4.1.2 on 2022-10-06 22:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dominaria', '0002_match_player_delete_post_match_player1_match_player2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(choices=[('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='dominaria.player')), ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='dominaria.player')), ('draw', 'draw')], max_length=100)),
                ('games_won_by_p1', models.PositiveIntegerField()),
                ('games_won_by_p2', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='dominaria.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='dominaria.player')),
            ],
            options={
                'unique_together': {('player1', 'player2')},
            },
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
