# Generated by Django 4.1.2 on 2022-10-07 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dominaria', '0003_matchup_delete_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='winner',
            field=models.CharField(choices=[(models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='dominaria.player'), None), (models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='dominaria.player'), None), ('draw', 'draw')], max_length=100),
        ),
    ]
